// eslint-disable-next-line
export const actionTypes = {
  EXHIBITS_SET_SEARCH_STRING: 'EXHIBITS_SET_SEARCH_STRING',
  EXHIBITS_SET_FILTER: 'EXHIBITS_SET_FILTER',
  EXHIBIT_CREATE: 'EXHIBIT_CREATE',
};
